### ISSUE TITLE
missing package.json

### ISSUE THREAD

**Issue by lludlow** [danomation/GPT-4-Discord-Voice#2]
grabbed this to play around with and it looks like the npm start command requires a package.json file. 

Interestingly enough when I created a simple one, it fails since it is using import statements inside the index.js

```
{
    "dependencies": {
        "@discordjs/voice": "^0.13.0",
        "discord.js": "^14.6.0"
    },
    "scripts": {
        "start": "node index.js"
    }
}
``` 

```
import { Client, GatewayIntentBits, Events } from 'discord.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.0
```

**Comment by lludlow** [comment]
Well, I worked around that and got it running... Doesn't seem to do anything except say !recording and the UID. I'll keep an eye on teh project and see if you manage to get further than me in the future.

**Comment by danomation** [comment]
The discord.js script just triggers the !record function when you start speaking. The !record function on the pycord side is triggered using an on message event, and it then records, processes, and speaks back.
This is  a temporary, and honestly somewhat hacky solution, because at the moment there's no python trigger for speaking. Part of the issue is the poor voice documentation from discord itself. Though some subclassing on the python gateway may work to make it purely python.

**Comment by danomation** [comment]
The next version I'm uploading uses that discord.js script to determine both the start and stop speaking status
